### PR TITLE
[MRG] Port all code to Python 3 with six

### PR DESCRIPTION
**Pull request by nippoo**

### CODE REVIEW

**Comment by nippoo** [comment]
Hm. This seems to pass all the tests, and, by some magic, work. @rossant or @thesamovar, want to test it?

**Comment by nippoo** [comment]
@thesamovar sorry about all the whitespace changes, my git + editor automatically does it so flake8 doesn't complain (no trailing whitespace on lines...) :(

**Comment by rossant** [comment]
worth setting up travis befor merging such a big PR?

**Comment by nippoo** [comment]
This is good to go @rossant. Don't make me make another commit, since I have to restart the build several times to deal with #49 and #48 ... ;)

**Comment by nippoo** [comment]
Or @thesamovar - good to review.

**Comment by rossant** [comment]
thanks @nippoo !

**Pull request merged**
