### PR TITLE
Fixed git version on Python3

### PR DESCRIPTION
**Pull request by nippoo**

### CODE REVIEW

**Comment by rossant** [comment]
works for me

it is `git-0.1.0-48-g3cf9ce75` souldn't it be 0.2.0?

**Comment by thesamovar** [comment]
Happy for this to be merged as soon as the issue that @rossant mentions is resolved. I did create a 0.2.0 tag so in principle this should work...

**Comment by nippoo** [comment]
Ah @rossant are you sure you haven't still checked out HEAD^1? Do a `git checkout upstream/master`...

You may need to `git fetch --tags`...

**Comment by rossant** [comment]
ok all good :) thx!

**Pull request merged**
