### PR TITLE
[WIP] Combine M and E steps

### LINKED ISSUE #15: Merge M and E steps and do not store covariance matrices
This would save an awful lot of RAM!

### PR DESCRIPTION
**Pull request by thesamovar**
Not ready to merge yet. Fixes #15.

### CODE REVIEW

**Comment by thesamovar** [comment]
Tests won't be passing but that's normal, I haven't updated them to reflect the internal changes in the code.

**Comment by thesamovar** [comment]
OK I think this is actually probably good to merge now, and has advantages for users (orders of magnitude less RAM usage). All tests pass and I can't see any reason why this would give poor results, but maybe it's worth running it on a couple of real data sets to see how well it does. Also would be interesting to see how much RAM and CPU it uses compared to master. I think we should schedule merging this after 0.2.0 is released that integrates with phy.

**Comment by nippoo** [comment]
@nsteinme do you want to test this out on at least one dataset? @thesamovar 0.2.0 won't be out for another 2/3 weeks or so, at least until we've got SpikeDetekt2 integrated with it (though it looks like this might make it into the 0.1.1 release around the middle of next week)

**Comment by nippoo** [comment]
so if @nsteinme is happy with the performance then I'll review and merge :)

**Comment by thesamovar** [comment]
OK, @nsteinme reports this is OK, tests are passing now, so merging.

**Pull request merged**
